# Generated by Django 4.2 on 2025-03-26 01:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hostname", models.CharField(max_length=255, unique=True)),
                ("ip_address", models.GenericIPAddressField()),
                (
                    "os_type",
                    models.CharField(
                        choices=[
                            ("windows", "Windows"),
                            ("linux", "Linux"),
                            ("macos", "macOS"),
                        ],
                        max_length=20,
                    ),
                ),
                ("os_version", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("error", "Error"),
                        ],
                        default="offline",
                        max_length=20,
                    ),
                ),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-last_seen"],
            },
        ),
    ]
